#!/usr/bin/env bash
set -euo pipefail

# Usage: post-review-comments.sh <session> <config> [manual]
# Reads platform config, formats review observations as markdown, posts to GitHub/GitLab
# Pass "manual" as 3rd arg to bypass auto_post check (used by /review-post)
# Stdout: POSTED/SKIP/WARN message
# Exit 0 always (never blocks the review)

session="${1:?Usage: post-review-comments.sh <session> <config> [manual]}"
config="${2:?Usage: post-review-comments.sh <session> <config> [manual]}"
mode="${3:-auto}"

if [[ ! -f "$session" ]]; then
  echo "WARN: session file not found: $session"
  exit 0
fi

if [[ ! -f "$config" ]]; then
  echo "WARN: config file not found: $config"
  exit 0
fi

# Read platform config
platform_type=$(jq -r '.platform.type // empty' "$config" 2>/dev/null || true)
auto_post=$(jq -r '.platform.auto_post // false' "$config" 2>/dev/null || true)

if [[ -z "$platform_type" || "$platform_type" == "null" ]]; then
  echo "SKIP: platform not configured"
  exit 0
fi

if [[ "$auto_post" != "true" && "$mode" != "manual" ]]; then
  echo "SKIP: auto_post disabled"
  exit 0
fi

# Verify CLI is available
if [[ "$platform_type" == "github" ]]; then
  if ! command -v gh &>/dev/null; then
    echo "WARN: gh CLI not found in PATH. Install: https://cli.github.com"
    exit 0
  fi
elif [[ "$platform_type" == "gitlab" ]]; then
  if ! command -v glab &>/dev/null; then
    echo "WARN: glab CLI not found in PATH. Install: https://gitlab.com/gitlab-org/cli"
    exit 0
  fi
else
  echo "WARN: unknown platform type: $platform_type"
  exit 0
fi

# Detect PR/MR for current branch
branch=$(git branch --show-current 2>/dev/null || true)
if [[ -z "$branch" ]]; then
  echo "SKIP: not on a branch (detached HEAD?)"
  exit 0
fi

pr_number=""
if [[ "$platform_type" == "github" ]]; then
  pr_number=$(gh pr list --head "$branch" --json number --jq '.[0].number' 2>/dev/null || true)
elif [[ "$platform_type" == "gitlab" ]]; then
  pr_number=$(glab mr list --source-branch "$branch" -o json 2>/dev/null | jq -r '.[0].iid // empty' 2>/dev/null || true)
fi

if [[ -z "$pr_number" ]]; then
  echo "SKIP: no open PR/MR found for branch $branch"
  exit 0
fi

# Read language for localized labels
lang=$(jq -r '.options.language // "fr"' "$config" 2>/dev/null || echo "fr")
ai_fix_prompt=$(jq -r '.platform.inline_comments.ai_fix_prompt // false' "$config" 2>/dev/null || echo "false")

# Determine session type (review or followup)
session_type=$(jq -r '.type // "review"' "$session")

# Build the comment body via jq
body=$(jq -r --arg lang "$lang" --arg session_type "$session_type" --arg ai_fix "$ai_fix_prompt" '
  # Localized labels
  (if $lang == "en" then
    {
      blocking_title: "Blocking observations",
      suggestions_title: "Suggestions",
      verdict_title: "Verdict",
      verdict_blocking: "blocking observation(s) — changes required before merge.",
      verdict_clean: "No blocking observations — ready to merge.",
      files_label: "files",
      followup_resolved: "Resolved",
      followup_partial: "Partially resolved",
      followup_unresolved: "Unresolved",
      followup_verdict_clean: "All blocking observations resolved — ready to merge.",
      followup_verdict_remaining: "blocking observation(s) remaining.",
      generated_by: "Generated by scd-review"
    }
  else
    {
      blocking_title: "Observations bloquantes",
      suggestions_title: "Suggestions",
      verdict_title: "Verdict",
      verdict_blocking: "observation(s) bloquante(s) — corrections requises avant merge.",
      verdict_clean: "Aucune observation bloquante — pret a merger.",
      files_label: "fichiers",
      followup_resolved: "Resolus",
      followup_partial: "Partiellement resolus",
      followup_unresolved: "Non resolus",
      followup_verdict_clean: "Toutes les observations bloquantes resolues — pret a merger.",
      followup_verdict_remaining: "observation(s) bloquante(s) restante(s).",
      generated_by: "Genere par scd-review"
    }
  end) as $l |

  .branch as $branch |
  .summary as $s |

  if $session_type == "followup" then
    # Followup format
    .round as $round |
    "## Code Review Followup (round \($round)) — \($branch)\n" +
    "\n" +
    "**\(.files | length)** \($l.files_label) | \($l.followup_resolved): \($s.resolved // 0) | \($l.followup_partial): \($s.partially_resolved // 0) | \($l.followup_unresolved): \($s.unresolved // 0)\n" +
    "\n" +

    # Corrections with blocking observations
    ([.files[] | select(.review_type == "correction" and (.observations | map(select(.severity == "bloquant")) | length) > 0)] |
      if length > 0 then
        "### \($l.blocking_title)\n\n" +
        (map(
          "**\(.path)**\n" +
          ([.observations[] | select(.severity == "bloquant") |
            "- \(if .level == "red" then "🔴" elif .level == "yellow" then "🟡" else "🟢" end) **\(.criterion)** — \(.text)" +
            (if .detail then "\n  > \(.detail)" else "" end) +
            (if ($ai_fix == "true") and .fix_prompt then
               "\n  <details><summary>🤖 AI Fix</summary>\n\n  ```ai-fix\n  file: \(.fix_prompt.file)\n  line: \(.fix_prompt.line)\n  action: \(.fix_prompt.action)\n  description: \(.fix_prompt.description)\n  ```\n  </details>"
             else "" end)
          ] | join("\n"))
        ) | join("\n\n")) + "\n\n"
      else ""
      end
    ) +

    # Resolution summary
    "### \($l.verdict_title)\n\n" +
    (
      ((.files | map(select(.review_type == "correction" or .review_type == "unaddressed")) |
        map(select(.resolution == "unresolved" or .resolution == "partially_resolved")) | length) // 0) as $remaining |
      if $remaining > 0 then
        "⚠️ **\($remaining)** \($l.followup_verdict_remaining)"
      else
        "✅ \($l.followup_verdict_clean)"
      end
    ) +
    "\n\n---\n_\($l.generated_by)_"

  else
    # Standard review format
    "## Code Review — \($branch)\n" +
    "\n" +
    "**\(.files | length)** \($l.files_label) | 🟢 \($s.green) | 🟡 \($s.yellow) | 🔴 \($s.red) | **B** \($s.blocking // 0)\n" +
    "\n" +

    # Blocking observations grouped by file
    ([.files[] | select((.observations | map(select(.severity == "bloquant")) | length) > 0)] |
      if length > 0 then
        "### \($l.blocking_title)\n\n" +
        (map(
          "**\(.path)**\n" +
          ([.observations[] | select(.severity == "bloquant") |
            "- \(if .level == "red" then "🔴" elif .level == "yellow" then "🟡" else "🟢" end) **\(.criterion)** — \(.text)" +
            (if .detail then "\n  > \(.detail)" else "" end) +
            (if ($ai_fix == "true") and .fix_prompt then
               "\n  <details><summary>🤖 AI Fix</summary>\n\n  ```ai-fix\n  file: \(.fix_prompt.file)\n  line: \(.fix_prompt.line)\n  action: \(.fix_prompt.action)\n  description: \(.fix_prompt.description)\n  ```\n  </details>"
             else "" end)
          ] | join("\n"))
        ) | join("\n\n")) + "\n\n"
      else ""
      end
    ) +

    # Suggestions in collapsible
    ([.files[] | .path as $p | .observations[] | select(.severity == "suggestion" and .level != "green") | {path: $p, obs: .}] |
      if length > 0 then
        "<details>\n<summary>\($l.suggestions_title) (\(length))</summary>\n\n" +
        (group_by(.path) | map(
          "**\(.[0].path)**\n" +
          ([.[].obs |
            "- \(if .level == "red" then "🔴" elif .level == "yellow" then "🟡" else "🟢" end) **\(.criterion)** — \(.text)" +
            (if .detail then "\n  > \(.detail)" else "" end) +
            (if ($ai_fix == "true") and .fix_prompt then
               "\n  <details><summary>🤖 AI Fix</summary>\n\n  ```ai-fix\n  file: \(.fix_prompt.file)\n  line: \(.fix_prompt.line)\n  action: \(.fix_prompt.action)\n  description: \(.fix_prompt.description)\n  ```\n  </details>"
             else "" end)
          ] | join("\n"))
        ) | join("\n\n")) + "\n\n</details>\n\n"
      else ""
      end
    ) +

    # Verdict
    "### \($l.verdict_title)\n\n" +
    (
      ($s.blocking // 0) as $b |
      if $b > 0 then
        "⚠️ **\($b)** \($l.verdict_blocking)"
      else
        "✅ \($l.verdict_clean)"
      end
    ) +
    "\n\n---\n_\($l.generated_by)_"
  end
' "$session")

if [[ -z "$body" ]]; then
  echo "WARN: failed to generate comment body"
  exit 0
fi

# Determine review action for GitHub
if [[ "$platform_type" == "github" ]]; then
  blocking_count=$(jq '.summary.blocking // 0' "$session")

  if [[ "$session_type" == "followup" ]]; then
    # Followup: check if all resolved
    unresolved=$(jq '[.files[] | select(.review_type == "correction" or .review_type == "unaddressed") | select(.resolution == "unresolved" or .resolution == "partially_resolved")] | length' "$session")
    if [[ "$unresolved" -eq 0 ]]; then
      gh pr review "$pr_number" --approve --body "$body" 2>/dev/null && echo "POSTED: approved PR #$pr_number" || echo "WARN: gh pr review failed"
    else
      gh pr review "$pr_number" --request-changes --body "$body" 2>/dev/null && echo "POSTED: requested changes on PR #$pr_number" || echo "WARN: gh pr review failed"
    fi
  else
    # Standard review
    if [[ "$blocking_count" -gt 0 ]]; then
      gh pr review "$pr_number" --request-changes --body "$body" 2>/dev/null && echo "POSTED: requested changes on PR #$pr_number" || echo "WARN: gh pr review failed"
    else
      gh pr review "$pr_number" --comment --body "$body" 2>/dev/null && echo "POSTED: commented on PR #$pr_number" || echo "WARN: gh pr review failed"
    fi
  fi

elif [[ "$platform_type" == "gitlab" ]]; then
  glab mr note "$pr_number" --message "$body" 2>/dev/null && echo "POSTED: commented on MR !$pr_number" || echo "WARN: glab mr note failed"
fi

exit 0
